#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     Touch,               sensorHiTechnicTouchMux)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    ,                     tServoNormal)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "HTTMUX-driver.h"

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

static const int kServoStartingPosition = 128;
static const int kServoEndingPosition = kServoStartingPosition + 100;

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  int delta = 2;                        // Create int 'delta' to the be Servo Change Rate.

  servoChangeRate[servo1] = delta;      // Slow the Servo Change Rate down to only 'delta' positions per update.

  while(ServoValue[servo1] != kServoStartingPosition) // While the ServoValue of servo1 is less than 128.
  {
    servo[servo1] = kServoStartingPosition; // Move servo1 to position to 128.
  }

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  // wait for the touch sensor on port 1 to the multiplexer to be pressed
  while (!HTTMUXisActive(Touch, 1))
  {
    nxtDisplayTextLine(1, "Waiting for TS 1");
  }

  ClearTimer(T1); // reset the timer

  // trigger servo
  while(ServoValue[servo1] != kServoEndingPosition)
  {
    servo[servo1] = kServoEndingPosition;
  }

  // start racing up the poll
  motor[motorD] = -100;
  motor[motorE] = 100;

  // loop as long as there is time left and the touch sensor hasn't touched the top
  while (time1[T1] < 10000 && !HTTMUXisActive(Touch, 2))
  {
    nxtDisplayTextLine(2, "Waiting for TS 2");
    nxtDisplayTextLine(3, " or 10 seconds");
    nxtDisplayTextLine(4, "   %5d", time1[T1]);
  }

  // back down the poll at a slower rate
  motor[motorD] = 50;
  motor[motorE] = -50;

  // keep going until we touch the bottom
  while (time1[T1] < 20000 && !HTTMUXisActive(Touch, 3))
  {
    nxtDisplayTextLine(5, "Waiting for TS 3");
  }

  // stop the motors
  motor[motorD] = 0;
  motor[motorE] = 0;

  // use the servo to open the motors
  while(ServoValue[servo1] != kServoStartingPosition)
  {
    servo[servo1] = kServoStartingPosition;
  }
}
